### ISSUE TITLE
Incorrect restructuring of multi-head loop

### ISSUE THREAD

**Issue by sklam** [numba/numba-rvsdg#46]
From `DEBUGGRAPH=1 pytest numba_rvsdg/tests/test_mock_asm.py::test_mock_scfg_fuzzer_case9` in #42.

CFG:

![Screenshot 2023-04-18 at 4 24 11 PM](https://user-images.githubusercontent.com/1929845/232908418-d9517e56-f78e-4846-b77d-dfd794f73785.png)

Loop restructured:

![Screenshot 2023-04-18 at 4 24 50 PM](https://user-images.githubusercontent.com/1929845/232908535-a901e939-27d8-4c24-8e36-40dbe547688d.png)

The loop should switch between _offset 4_ and _offset 6_ blocks but there are no assignment to control-variable _a_ within  the loop.

**Comment by sklam** [comment]
Same problem in `DEBUGGRAPH=1 pytest numba_rvsdg/tests/test_mock_asm.py::test_mock_scfg_fuzzer_case153 -s`

**Comment by esc** [comment]
This graph variation is already present in the the test suite:

https://github.com/numba/numba-rvsdg/blob/main/numba_rvsdg/tests/test_transforms.py#L552

The input looks like:

<img width="476" alt="Screen Shot 2023-04-24 at 13 58 42" src="https://user-images.githubusercontent.com/41563/233990244-4034368b-b65c-42bf-ad73-3a07250b5233.png">

And the output like:

<img width="599" alt="Screen Shot 2023-04-24 at 13 59 01" src="https://user-images.githubusercontent.com/41563/233990320-f3d2ddc9-9fd6-4d8e-89e1-b2f0299155f6.png">

We can see here, that the variable `a` isn't being set in the assignments. I initially though, that this would be the result of a double header in the loop, but looking at the Fig 3. tests we see that:

<img width="682" alt="Screen Shot 2023-04-24 at 14 03 24" src="https://user-images.githubusercontent.com/41563/233990724-07065a9c-0a05-41d3-9523-e7ccb6af7ed6.png">


It does work correctly in this case. So my next guess is that this may be related to the loop having only a single exit.

The reason this was not caught by the testing suite, is because the YAML tests only compare the structure of the graph, but not the "contents" of each block. Additional work on the testing suite will be needed to allow for encoding this.

**Comment by esc** [comment]
I have created a patch to fix this issue, it was indeed the case, when there were two headers but only one exit:

```
diff --git i/numba_rvsdg/core/transformations.py w/numba_rvsdg/core/transformations.py
index b3d59811b6..0ba8b2a493 100644
--- i/numba_rvsdg/core/transformations.py
+++ w/numba_rvsdg/core/transformations.py
@@ -151,7 +151,7 @@ def loop_restructure_helper(scfg: SCFG, loop: Set[Label]):
                     # the correct blocks
                     variable_assignment = {}
                     variable_assignment[backedge_variable] = reverse_lookup(backedge_value_table, loop_head)
-                    if needs_synth_exit:
+                    if needs_synth_exit or headers_were_unified:
                         variable_assignment[exit_variable] = reverse_lookup(header_value_table, jt)
                     # Update the backedge block - remove any existing backedges
                     # that point to the headers, no need to add a backedge,
```

And the correct rendering looks like:

<img width="630" alt="Screen Shot 2023-04-24 at 16 03 11" src="https://user-images.githubusercontent.com/41563/234020862-f12139df-cb11-4a19-9a3c-2d2e2877d6d1.png">

The blocks `SyntheticAssignment10` and `SyntheticAssignment12`  now also set a value for variable `a` which is the variable to be used in the `SyntheticHead6`
